version: 2

aliases:
  # Alias for any default options
  - &defaults
    docker:
      - image: debian:stretch

jobs:
  # Test build of the library
  build:
    <<: *defaults
    steps:
      - run:
          name: Install make and dependencies
          command: apt-get update && apt-get install -y binutils make
      - checkout
      - run:
          name: Build via make
          command: make

  test:
    <<: *defaults
    steps:
      - run:
          name: Install make and dependencies
          command: apt-get update && apt-get install -y binutils make
      - checkout
      - run:
          name: Run main tests
          command: cd test && make && ./a.out
      - run:
          name: Run test and assert successful return code
          command: cd test && make test-n && ./test-1.out
      - run:
          name: Run test and assert failing return code
          command: bash -c "cd test && make test-n && ./test-2.out; if [[ \$? -eq 2 ]]; then exit 0; else exit 1; fi"

workflows:
  version: 2
  everything:
    jobs: # For reference, all jobs run in parallel
      - build
      - test
